---
- name: Install acl for become_user
  ansible.builtin.apt:
    name: acl
    state: present

- name: Install PostgreSQL 16
  ansible.builtin.apt:
    name:
      - postgresql-16
      - python3-psycopg2
    state: present

- name: Install PostgreSQL 16
  ansible.builtin.apt:
    name:
      - postgresql-16
      - python3-psycopg2
    state: present

- name: Start and enable PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes

- name: Configure listen_addresses
  ansible.builtin.lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?listen_addresses'
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Copy pg_hba.conf
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/16/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
  notify: restart postgresql

- name: Create database
  community.postgresql.postgresql_db:
    name: app_db
  become: yes
  become_user: postgres
  become_flags: '--login'

- name: Create user
  community.postgresql.postgresql_user:
    name: app_user
    password: "changeme123"
    db: app_db
    priv: "ALL"
  become: yes
  become_user: postgres
  become_flags: '--login'

