app:
  hosts:
    vm1:
      ansible_host: 10.10.10.103
      ansible_user: makl
db:
  hosts:
    vm2:
      ansible_host: 10.10.10.104
      ansible_user: makl
awx:
  hosts:
    vm3:
      ansible_host: 10.10.10.105
      ansible_user: makl
