---
- name: Gather facts from db and awx
  hosts: db:awx
  gather_facts: yes
  tasks: []

- name: Deploy PostgreSQL
  hosts: db
  become: yes
  roles:
    - postgresql

- name: Deploy Backend
  hosts: app
  gather_facts: no
  become: yes
  roles:
    - backend
